CREATE TABLE install.project_locations (
    project_id character varying(50) ENCODE lzo,
    site_id character varying(36) ENCODE lzo,
    installation_id character varying(36) ENCODE lzo,
    company_id integer ENCODE az64,
    account_id character varying(30) ENCODE lzo,
    mapping_id character varying(36) ENCODE lzo,
    event_retry_count integer ENCODE az64,
    event_triggered boolean ENCODE raw,
    event_retry_time character varying(32) ENCODE lzo,
    is_deleted boolean ENCODE raw,
    created_by character varying(30) ENCODE lzo,
    created_at character varying(32) ENCODE lzo,
    modified_by character varying(30) ENCODE lzo,
    modified_at character varying(32) ENCODE lzo,
    correlation_id character varying(36) ENCODE lzo,
    kafka_topic character varying(128) ENCODE lzo,
    kafka_partition integer ENCODE az64,
    kafka_offset bigint ENCODE az64,
    kafka_timestamp bigint ENCODE az64,
    kafka_timestamp_type character varying(32) ENCODE lzo,
    kafka_datetime character varying(32) ENCODE lzo,
    kafka_key character varying(50) ENCODE lzo,
    etl_process_timestamp bigint ENCODE az64,
    etl_process_utc_ts character varying(32) ENCODE lzo,
    record_creation_ts timestamp without time zone ENCODE az64,
    record_update_ts timestamp without time zone ENCODE az64
);