CREATE TABLE utils.date (
    key numeric(38, 0) NOT NULL ENCODE az64,
    formatted_date date NOT NULL ENCODE az64,
    month numeric(38, 0) NOT NULL ENCODE az64,
    month_name character varying(15) NOT NULL ENCODE lzo,
    day numeric(38, 0) NOT NULL ENCODE az64,
    day_name character varying(15) NOT NULL ENCODE lzo,
    quarter numeric(38, 0) NOT NULL ENCODE az64,
    quarter_name character varying(2) NOT NULL ENCODE lzo,
    year numeric(38, 0) NOT NULL ENCODE az64,
    week_number numeric(38, 0) NOT NULL ENCODE az64,
    first_dayof_week date NOT NULL ENCODE az64,
    last_dayof_week date NOT NULL ENCODE az64,
    first_dayof_report_week date NOT NULL ENCODE az64,
    last_dayof_report_week date NOT NULL ENCODE az64,
    first_dayof_month date NOT NULL ENCODE az64,
    last_dayof_month date NOT NULL ENCODE az64,
    first_dayof_quarter date NOT NULL ENCODE az64,
    last_dayof_quarter date NOT NULL ENCODE az64,
    first_dayof_year date NOT NULL ENCODE az64,
    last_dayof_year date NOT NULL ENCODE az64,
    sprint_bill_start date NOT NULL ENCODE az64,
    sprint_bill_end date NOT NULL ENCODE az64,
    first_day_of_fiscal_week date NOT NULL ENCODE az64,
    last_day_of_fiscal_week date NOT NULL ENCODE az64,
    first_day_of_fiscal_month date NOT NULL ENCODE az64,
    last_day_of_fiscal_month date NOT NULL ENCODE az64,
    first_day_of_fiscal_quarter date NOT NULL ENCODE az64,
    last_day_of_fiscal_quarter date NOT NULL ENCODE az64,
    first_day_of_fiscal_year date NOT NULL ENCODE az64,
    last_day_of_fiscal_year date NOT NULL ENCODE az64,
    fiscal_week_number numeric(38, 0) NOT NULL ENCODE az64,
    prior_first_day_of_fiscal_month date NOT NULL ENCODE az64,
    prior_last_day_of_fiscal_month date NOT NULL ENCODE az64,
    first_dayof_monday_week date NOT NULL ENCODE az64,
    last_dayof_monday_week date NOT NULL ENCODE az64,
    day_in_year numeric(38, 0) NOT NULL ENCODE az64,
    prior_first_dayof_month date ENCODE az64,
    prior_last_dayof_month date ENCODE az64,
    first_fiscal_day date ENCODE az64,
    fiscal_year_month_int numeric(38, 0) ENCODE az64,
    first_day_of_wed_week date ENCODE az64,
    last_day_of_wed_week date ENCODE az64,
    year_week_number numeric(38, 0) ENCODE az64,
    year_month_number numeric(38, 0) ENCODE az64,
    edw_creation_date timestamp without time zone NOT NULL ENCODE az64,
    edw_update_date timestamp without time zone NOT NULL ENCODE az64
) DISTSTYLE AUTO;